---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/todo_items":
    post:
      summary: Attaches todo item to todo list
      tags:
        - TodoItem
      parameters: []
      responses:
        "201":
          description: todo list created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                todo_list_id:
                  type: number
              required:
                - body
  "/todo_items/{id}/toggle":
    patch:
      summary: Toggles completed or not completed for one todo item
      tags:
        - TodoItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: todo list toggled
  "/todo_lists":
    post:
      summary: Creates a todo list
      tags:
        - TodoList
      parameters: []
      responses:
        "201":
          description: blog created
        "422":
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
                - title
  "/todo_lists/{id}":
    get:
      summary: Retreive a todo list
      tags:
        - TodoList
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: one todo list retreived
servers:
  - url: https://todoapiexample-production.up.railway.app/
