---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/todo_items":
    post:
      summary: Attaches todo item to todo list
      tags:
      - TodoItem
      parameters: []
      responses:
        '201':
          description: todo list created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                todo_list_id:
                  type: number
              required:
              - body
  "/todo_items/{id}":
    delete:
      summary: Delete todo item
      tags:
      - TodoItem
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: one todo item removed
  "/todo_items/{id}/toggle":
    patch:
      summary: Toggles completed or not completed for one todo item
      tags:
      - TodoItem
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: todo list toggled
  "/todo_lists":
    post:
      summary: Creates a todo list
      tags:
      - TodoList
      parameters: []
      responses:
        '201':
          description: blog created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
              - title
  "/todo_lists/{id}":
    get:
      summary: Retrieve a todo list
      tags:
      - TodoList
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: one todo list retrieved
    delete:
      summary: Delete todo list
      tags:
      - TodoList
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: one todo list removed
servers:
- url: http://127.0.0.1:3000
