---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/todo_items":
    post:
      summary: Attaches todo item to todo list
      tags:
      - TodoItem
      parameters: []
      responses:
        '201':
          description: todo list created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                todo_list_id:
                  type: number
              required:
              - body
  "/todo_lists":
    post:
      summary: Creates a todo list
      tags:
      - TodoList
      parameters: []
      responses:
        '201':
          description: blog created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
              - title
    get:
      summary: Retreive todo list
      tags:
      - TodoList
      parameters: []
      responses:
        '200':
          description: one todo list retreived
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
              - id
servers:
- url: http://localhost:3000
